/*
 * Copyright (c) 2014 Stephan D. Cote' - All rights reserved.
 * 
 * This program and the accompanying materials are made available under the 
 * terms of the MIT License which accompanies this distribution, and is 
 * available at http://creativecommons.org/licenses/MIT/
 *
 * Contributors:
 *   Stephan D. Cote 
 *      - Initial concept and initial implementation
 */
package coyote.commons.feature;

/**
 * 
 */
public enum MenuIcon {
  ADJUST( "adjust"), ADN( "adn"), ALIGN_CENTER( "align-center"), ALIGN_JUSTIFY( "align-justify"), ALIGN_LEFT( "align-left"), ALIGN_RIGHT( "align-right"), AMBULANCE( "ambulance"), ANCHOR( "anchor"), ANDROID( "android"), ANGELLIST( "angellist"), ANGLE_DOUBLE_DOWN( "angle-double-down"), ANGLE_DOUBLE_LEFT( "angle-double-left"), ANGLE_DOUBLE_RIGHT( "angle-double-right"), ANGLE_DOUBLE_UP( "angle-double-up"), ANGLE_DOWN( "angle-down"), ANGLE_LEFT( "angle-left"), ANGLE_RIGHT( "angle-right"), ANGLE_UP( "angle-up"), APPLE( "apple"), ARCHIVE( "archive"), AREA_CHART( "area-chart"), ARROW_CIRCLE_DOWN( "arrow-circle-down"), ARROW_CIRCLE_LEFT( "arrow-circle-left"), ARROW_CIRCLE_O_DOWN( "arrow-circle-o-down"), ARROW_CIRCLE_O_LEFT( "arrow-circle-o-left"), ARROW_CIRCLE_O_RIGHT( "arrow-circle-o-right"), ARROW_CIRCLE_O_UP( "arrow-circle-o-up"), ARROW_CIRCLE_RIGHT( "arrow-circle-right"), ARROW_CIRCLE_UP( "arrow-circle-up"), ARROW_DOWN( "arrow-down"), ARROW_LEFT( "arrow-left"), ARROW_RIGHT( "arrow-right"), ARROW_UP( "arrow-up"), ARROWS(
      "arrows"), ARROWS_ALT( "arrows-alt"), ARROWS_H( "arrows-h"), ARROWS_V( "arrows-v"), ASTERISK( "asterisk"), AT( "at"), AUTOMOBILE( "automobile"), BACKWARD( "backward"), BAN( "ban"), BANK( "bank"), BAR_CHART( "bar-chart"), BAR_CHART_O( "bar-chart-o"), BARCODE( "barcode"), BARS( "bars"), BEER( "beer"), BEHANCE( "behance"), BEHANCE_SQUARE( "behance-square"), BELL( "bell"), BELL_O( "bell-o"), BELL_SLASH( "bell-slash"), BELL_SLASH_O( "bell-slash-o"), BICYCLE( "bicycle"), BINOCULARS( "binoculars"), BIRTHDAY_CAKE( "birthday-cake"), BITBUCKET( "bitbucket"), BITBUCKET_SQUARE( "bitbucket-square"), BITCOIN( "bitcoin"), BOLD( "bold"), BOLT( "bolt"), BOMB( "bomb"), BOOK( "book"), BOOKMARK( "bookmark"), BOOKMARK_O( "bookmark-o"), BRIEFCASE( "briefcase"), BTC( "btc"), BUG( "bug"), BUILDING( "building"), BUILDING_O( "building-o"), BULLHORN( "bullhorn"), BULLSEYE( "bullseye"), BUS( "bus"), CAB( "cab"), CALCULATOR( "calculator"), CALENDAR( "calendar"), CALENDAR_O( "calendar-o"), CAMERA( "camera"), CAMERA_RETRO(
      "camera-retro"), CAR( "car"), CARET_DOWN( "caret-down"), CARET_LEFT( "caret-left"), CARET_RIGHT( "caret-right"), CARET_SQUARE_O_DOWN( "caret-square-o-down"), CARET_SQUARE_O_LEFT( "caret-square-o-left"), CARET_SQUARE_O_RIGHT( "caret-square-o-right"), CARET_SQUARE_O_UP( "caret-square-o-up"), CARET_UP( "caret-up"), CC( "cc"), CC_AMEX( "cc-amex"), CC_DISCOVER( "cc-discover"), CC_MASTERCARD( "cc-mastercard"), CC_PAYPAL( "cc-paypal"), CC_STRIPE( "cc-stripe"), CC_VISA( "cc-visa"), CERTIFICATE( "certificate"), CHAIN( "chain"), CHAIN_BROKEN( "chain-broken"), CHECK( "check"), CHECK_CIRCLE( "check-circle"), CHECK_CIRCLE_O( "check-circle-o"), CHECK_SQUARE( "check-square"), CHECK_SQUARE_O( "check-square-o"), CHEVRON_CIRCLE_DOWN( "chevron-circle-down"), CHEVRON_CIRCLE_LEFT( "chevron-circle-left"), CHEVRON_CIRCLE_RIGHT( "chevron-circle-right"), CHEVRON_CIRCLE_UP( "chevron-circle-up"), CHEVRON_DOWN( "chevron-down"), CHEVRON_LEFT( "chevron-left"), CHEVRON_RIGHT( "chevron-right"), CHEVRON_UP( "chevron-up"), CHILD(
      "child"), CIRCLE( "circle"), CIRCLE_O( "circle-o"), CIRCLE_O_NOTCH( "circle-o-notch"), CIRCLE_THIN( "circle-thin"), CLIPBOARD( "clipboard"), CLOCK_O( "clock-o"), CLOSE( "close"), CLOUD( "cloud"), CLOUD_DOWNLOAD( "cloud-download"), CLOUD_UPLOAD( "cloud-upload"), CNY( "cny"), CODE( "code"), CODE_FORK( "code-fork"), CODEPEN( "codepen"), COFFEE( "coffee"), COG( "cog"), COGS( "cogs"), COLUMNS( "columns"), COMMENT( "comment"), COMMENT_O( "comment-o"), COMMENTS( "comments"), COMMENTS_O( "comments-o"), COMPASS( "compass"), COMPRESS( "compress"), COPY( "copy"), COPYRIGHT( "copyright"), CREDIT_CARD( "credit-card"), CROP( "crop"), CROSSHAIRS( "crosshairs"), CSS3( "css3"), CUBE( "cube"), CUBES( "cubes"), CUT( "cut"), CUTLERY( "cutlery"), DASHBOARD( "dashboard"), DATABASE( "database"), DEDENT( "dedent"), DELICIOUS( "delicious"), DESKTOP( "desktop"), DEVIANTART( "deviantart"), DIGG( "digg"), DOLLAR( "dollar"), DOT_CIRCLE_O( "dot-circle-o"), DOWNLOAD( "download"), DRIBBBLE( "dribbble"), DROPBOX( "dropbox"), DRUPAL(
      "drupal"), EDIT( "edit"), EJECT( "eject"), ELLIPSIS_H( "ellipsis-h"), ELLIPSIS_V( "ellipsis-v"), EMPIRE( "empire"), ENVELOPE( "envelope"), ENVELOPE_O( "envelope-o"), ENVELOPE_SQUARE( "envelope-square"), ERASER( "eraser"), EUR( "eur"), EURO( "euro"), EXCHANGE( "exchange"), EXCLAMATION( "exclamation"), EXCLAMATION_CIRCLE( "exclamation-circle"), EXCLAMATION_TRIANGLE( "exclamation-triangle"), EXPAND( "expand"), EXTERNAL_LINK( "external-link"), EXTERNAL_LINK_SQUARE( "external-link-square"), EYE( "eye"), EYE_SLASH( "eye-slash"), EYEDROPPER( "eyedropper"), FACEBOOK( "facebook"), FACEBOOK_SQUARE( "facebook-square"), FAST_BACKWARD( "fast-backward"), FAST_FORWARD( "fast-forward"), FAX( "fax"), FEMALE( "female"), FIGHTER_JET( "fighter-jet"), FILE( "file"), FILE_ARCHIVE_O( "file-archive-o"), FILE_AUDIO_O( "file-audio-o"), FILE_CODE_O( "file-code-o"), FILE_EXCEL_O( "file-excel-o"), FILE_IMAGE_O( "file-image-o"), FILE_MOVIE_O( "file-movie-o"), FILE_O( "file-o"), FILE_PDF_O( "file-pdf-o"), FILE_PHOTO_O(
      "file-photo-o"), FILE_PICTURE_O( "file-picture-o"), FILE_POWERPOINT_O( "file-powerpoint-o"), FILE_SOUND_O( "file-sound-o"), FILE_TEXT( "file-text"), FILE_TEXT_O( "file-text-o"), FILE_VIDEO_O( "file-video-o"), FILE_WORD_O( "file-word-o"), FILE_ZIP_O( "file-zip-o"), FILES_O( "files-o"), FILM( "film"), FILTER( "filter"), FIRE( "fire"), FIRE_EXTINGUISHER( "fire-extinguisher"), FLAG( "flag"), FLAG_CHECKERED( "flag-checkered"), FLAG_O( "flag-o"), FLASH( "flash"), FLASK( "flask"), FLICKR( "flickr"), FLOPPY_O( "floppy-o"), FOLDER( "folder"), FOLDER_O( "folder-o"), FOLDER_OPEN( "folder-open"), FOLDER_OPEN_O( "folder-open-o"), FONT( "font"), FORWARD( "forward"), FOURSQUARE( "foursquare"), FROWN_O( "frown-o"), FUTBOL_O( "futbol-o"), GAMEPAD( "gamepad"), GAVEL( "gavel"), GBP( "gbp"), GE( "ge"), GEAR( "gear"), GEARS( "gears"), GIFT( "gift"), GIT( "git"), GIT_SQUARE( "git-square"), GITHUB( "github"), GITHUB_ALT( "github-alt"), GITHUB_SQUARE( "github-square"), GITTIP( "gittip"), GLASS( "glass"), GLOBE( "globe"), GOOGLE(
      "google"), GOOGLE_PLUS( "google-plus"), GOOGLE_PLUS_SQUARE( "google-plus-square"), GOOGLE_WALLET( "google-wallet"), GRADUATION_CAP( "graduation-cap"), GROUP( "group"), H_SQUARE( "h-square"), HACKER_NEWS( "hacker-news"), HAND_O_DOWN( "hand-o-down"), HAND_O_LEFT( "hand-o-left"), HAND_O_RIGHT( "hand-o-right"), HAND_O_UP( "hand-o-up"), HDD_O( "hdd-o"), HEADER( "header"), HEADPHONES( "headphones"), HEART( "heart"), HEART_O( "heart-o"), HISTORY( "history"), HOME( "home"), HOSPITAL_O( "hospital-o"), HTML5( "html5"), ILS( "ils"), IMAGE( "image"), INBOX( "inbox"), INDENT( "indent"), INFO( "info"), INFO_CIRCLE( "info-circle"), INR( "inr"), INSTAGRAM( "instagram"), INSTITUTION( "institution"), IOXHOST( "ioxhost"), ITALIC( "italic"), JOOMLA( "joomla"), JPY( "jpy"), JSFIDDLE( "jsfiddle"), KEY( "key"), KEYBOARD_O( "keyboard-o"), KRW( "krw"), LANGUAGE( "language"), LAPTOP( "laptop"), LASTFM( "lastfm"), LASTFM_SQUARE( "lastfm-square"), LEAF( "leaf"), LEGAL( "legal"), LEMON_O( "lemon-o"), LEVEL_DOWN( "level-down"), LEVEL_UP(
      "level-up"), LIFE_BOUY( "life-bouy"), LIFE_BUOY( "life-buoy"), LIFE_RING( "life-ring"), LIFE_SAVER( "life-saver"), LIGHTBULB_O( "lightbulb-o"), LINE_CHART( "line-chart"), LINK( "link"), LINKEDIN( "linkedin"), LINKEDIN_SQUARE( "linkedin-square"), LINUX( "linux"), LIST( "list"), LIST_ALT( "list-alt"), LIST_OL( "list-ol"), LIST_UL( "list-ul"), LOCATION_ARROW( "location-arrow"), LOCK( "lock"), LONG_ARROW_DOWN( "long-arrow-down"), LONG_ARROW_LEFT( "long-arrow-left"), LONG_ARROW_RIGHT( "long-arrow-right"), LONG_ARROW_UP( "long-arrow-up"), MAGIC( "magic"), MAGNET( "magnet"), MAIL_FORWARD( "mail-forward"), MAIL_REPLY( "mail-reply"), MAIL_REPLY_ALL( "mail-reply-all"), MALE( "male"), MAP_MARKER( "map-marker"), MAXCDN( "maxcdn"), MEANPATH( "meanpath"), MEDKIT( "medkit"), MEH_O( "meh-o"), MICROPHONE( "microphone"), MICROPHONE_SLASH( "microphone-slash"), MINUS( "minus"), MINUS_CIRCLE( "minus-circle"), MINUS_SQUARE( "minus-square"), MINUS_SQUARE_O( "minus-square-o"), MOBILE( "mobile"), MOBILE_PHONE( "mobile-phone"), MONEY(
      "money"), MOON_O( "moon-o"), MORTAR_BOARD( "mortar-board"), MUSIC( "music"), NAVICON( "navicon"), NEWSPAPER_O( "newspaper-o"), OPENID( "openid"), OUTDENT( "outdent"), PAGELINES( "pagelines"), PAINT_BRUSH( "paint-brush"), PAPER_PLANE( "paper-plane"), PAPER_PLANE_O( "paper-plane-o"), PAPERCLIP( "paperclip"), PARAGRAPH( "paragraph"), PASTE( "paste"), PAUSE( "pause"), PAW( "paw"), PAYPAL( "paypal"), PENCIL( "pencil"), PENCIL_SQUARE( "pencil-square"), PENCIL_SQUARE_O( "pencil-square-o"), PHONE( "phone"), PHONE_SQUARE( "phone-square"), PHOTO( "photo"), PICTURE_O( "picture-o"), PIE_CHART( "pie-chart"), PIED_PIPER( "pied-piper"), PIED_PIPER_ALT( "pied-piper-alt"), PINTEREST( "pinterest"), PINTEREST_SQUARE( "pinterest-square"), PLANE( "plane"), PLAY( "play"), PLAY_CIRCLE( "play-circle"), PLAY_CIRCLE_O( "play-circle-o"), PLUG( "plug"), PLUS( "plus"), PLUS_CIRCLE( "plus-circle"), PLUS_SQUARE( "plus-square"), PLUS_SQUARE_O( "plus-square-o"), POWER_OFF( "power-off"), PRINT( "print"), PUZZLE_PIECE( "puzzle-piece"), QQ(
      "qq"), QRCODE( "qrcode"), QUESTION( "question"), QUESTION_CIRCLE( "question-circle"), QUOTE_LEFT( "quote-left"), QUOTE_RIGHT( "quote-right"), RA( "ra"), RANDOM( "random"), REBEL( "rebel"), RECYCLE( "recycle"), REDDIT( "reddit"), REDDIT_SQUARE( "reddit-square"), REFRESH( "refresh"), REMOVE( "remove"), RENREN( "renren"), REORDER( "reorder"), REPEAT( "repeat"), REPLY( "reply"), REPLY_ALL( "reply-all"), RETWEET( "retweet"), RMB( "rmb"), ROAD( "road"), ROCKET( "rocket"), ROTATE_LEFT( "rotate-left"), ROTATE_RIGHT( "rotate-right"), ROUBLE( "rouble"), RSS( "rss"), RSS_SQUARE( "rss-square"), RUB( "rub"), RUBLE( "ruble"), RUPEE( "rupee"), SAVE( "save"), SCISSORS( "scissors"), SEARCH( "search"), SEARCH_MINUS( "search-minus"), SEARCH_PLUS( "search-plus"), SEND( "send"), SEND_O( "send-o"), SHARE( "share"), SHARE_ALT( "share-alt"), SHARE_ALT_SQUARE( "share-alt-square"), SHARE_SQUARE( "share-square"), SHARE_SQUARE_O( "share-square-o"), SHEKEL( "shekel"), SHEQEL( "sheqel"), SHIELD( "shield"), SHOPPING_CART(
      "shopping-cart"), SIGN_IN( "sign-in"), SIGN_OUT( "sign-out"), SIGNAL( "signal"), SITEMAP( "sitemap"), SKYPE( "skype"), SLACK( "slack"), SLIDERS( "sliders"), SLIDESHARE( "slideshare"), SMILE_O( "smile-o"), SOCCER_BALL_O( "soccer-ball-o"), SORT( "sort"), SORT_ALPHA_ASC( "sort-alpha-asc"), SORT_ALPHA_DESC( "sort-alpha-desc"), SORT_AMOUNT_ASC( "sort-amount-asc"), SORT_AMOUNT_DESC( "sort-amount-desc"), SORT_ASC( "sort-asc"), SORT_DESC( "sort-desc"), SORT_DOWN( "sort-down"), SORT_NUMERIC_ASC( "sort-numeric-asc"), SORT_NUMERIC_DESC( "sort-numeric-desc"), SORT_UP( "sort-up"), SOUNDCLOUD( "soundcloud"), SPACE_SHUTTLE( "space-shuttle"), SPINNER( "spinner"), SPOON( "spoon"), SPOTIFY( "spotify"), SQUARE( "square"), SQUARE_O( "square-o"), STACK_EXCHANGE( "stack-exchange"), STACK_OVERFLOW( "stack-overflow"), STAR( "star"), STAR_HALF( "star-half"), STAR_HALF_EMPTY( "star-half-empty"), STAR_HALF_FULL( "star-half-full"), STAR_HALF_O( "star-half-o"), STAR_O( "star-o"), STEAM( "steam"), STEAM_SQUARE( "steam-square"), STEP_BACKWARD(
      "step-backward"), STEP_FORWARD( "step-forward"), STETHOSCOPE( "stethoscope"), STOP( "stop"), STRIKETHROUGH( "strikethrough"), STUMBLEUPON( "stumbleupon"), STUMBLEUPON_CIRCLE( "stumbleupon-circle"), SUBSCRIPT( "subscript"), SUITCASE( "suitcase"), SUN_O( "sun-o"), SUPERSCRIPT( "superscript"), SUPPORT( "support"), TABLE( "table"), TABLET( "tablet"), TACHOMETER( "tachometer"), TAG( "tag"), TAGS( "tags"), TASKS( "tasks"), TAXI( "taxi"), TENCENT_WEIBO( "tencent-weibo"), TERMINAL( "terminal"), TEXT_HEIGHT( "text-height"), TEXT_WIDTH( "text-width"), TH( "th"), TH_LARGE( "th-large"), TH_LIST( "th-list"), THUMB_TACK( "thumb-tack"), THUMBS_DOWN( "thumbs-down"), THUMBS_O_DOWN( "thumbs-o-down"), THUMBS_O_UP( "thumbs-o-up"), THUMBS_UP( "thumbs-up"), TICKET( "ticket"), TIMES( "times"), TIMES_CIRCLE( "times-circle"), TIMES_CIRCLE_O( "times-circle-o"), TINT( "tint"), TOGGLE_DOWN( "toggle-down"), TOGGLE_LEFT( "toggle-left"), TOGGLE_OFF( "toggle-off"), TOGGLE_ON( "toggle-on"), TOGGLE_RIGHT( "toggle-right"), TOGGLE_UP(
      "toggle-up"), TRASH( "trash"), TRASH_O( "trash-o"), TREE( "tree"), TRELLO( "trello"), TROPHY( "trophy"), TRUCK( "truck"), TRY( "try"), TTY( "tty"), TUMBLR( "tumblr"), TUMBLR_SQUARE( "tumblr-square"), TURKISH_LIRA( "turkish-lira"), TWITCH( "twitch"), TWITTER( "twitter"), TWITTER_SQUARE( "twitter-square"), UMBRELLA( "umbrella"), UNDERLINE( "underline"), UNDO( "undo"), UNIVERSITY( "university"), UNLINK( "unlink"), UNLOCK( "unlock"), UNLOCK_ALT( "unlock-alt"), UNSORTED( "unsorted"), UPLOAD( "upload"), USD( "usd"), USER( "user"), USER_MD( "user-md"), USERS( "users"), VIDEO_CAMERA( "video-camera"), VIMEO_SQUARE( "vimeo-square"), VINE( "vine"), VK( "vk"), VOLUME_DOWN( "volume-down"), VOLUME_OFF( "volume-off"), VOLUME_UP( "volume-up"), WARNING( "warning"), WECHAT( "wechat"), WEIBO( "weibo"), WEIXIN( "weixin"), WHEELCHAIR( "wheelchair"), WIFI( "wifi"), WINDOWS( "windows");

  private final String text;




  MenuIcon( String value ) {
    text = value;
  }




  public String toString() {
    return text;
  }

}
